#!/bin/bash
# Run this BEFORE every zip/upload to production.
# It removes locally-baked cache files that contain this machine's
# absolute paths (e.g. /home/sajibghosh/soft/sdf_main_web/...).
# Shipping those to production breaks storage_path()/config resolution
# there ("There is no existing directory at ... Permission denied").

set -e
cd "$(dirname "$0")"

echo "Clearing local Laravel caches so nothing machine-specific gets zipped..."
php artisan optimize:clear

# optimize:clear should already remove these, but delete explicitly as a
# hard guarantee in case any get regenerated by something running after it.
rm -f bootstrap/cache/config.php
rm -f bootstrap/cache/services.php
rm -f bootstrap/cache/packages.php
rm -f bootstrap/cache/routes-v6.php
rm -f bootstrap/cache/routes-v7.php
rm -f bootstrap/cache/events.php

echo "Done. bootstrap/cache/ now contains only:"
ls -la bootstrap/cache/
echo ""
echo "Safe to zip now. After uploading + fixing .env on the server, run:"
echo "  php artisan config:clear && php artisan optimize"
echo "ON THE SERVER (never zip a config cache built on this machine)."
