<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Finance Summary Report - SDF</title>
    <style>
        @page { margin: 80px 40px; }
        @font-face { font-family: 'SolaimanLipi'; font-weight: normal; src: url('{{ resource_path('fonts/SolaimanLipi.ttf') }}'); }
        @font-face { font-family: 'SolaimanLipi'; font-weight: bold; src: url('{{ resource_path('fonts/SolaimanLipi_Bold.ttf') }}'); }
        body { font-family: 'SolaimanLipi', 'Arial', sans-serif; font-size: 13px; color: #333; line-height: 1.5; }
        
        /* Header Section */
        header { position: fixed; top: -78px; left: 0; right: 0; border-bottom: 2px solid #2c3e50; padding-bottom: 5px; }
        .report-title { font-size: 20px; font-weight: bold; color: #2c3e50; }
        .meta-info { font-size: 10px; color: #555; text-align: right; }
        
        /* Stats Cards */
        .summary-grid { display: table; width: 100%; border-collapse: separate; border-spacing: 15px 0; margin: 20px -15px; }
        .stat-card { display: table-cell; background: #fdfdfd; padding: 15px; border: 1px solid #e1e4e8; border-radius: 4px; }
        .stat-label { font-size: 10px; text-transform: uppercase; color: #666; }
        .stat-value { font-size: 16px; font-weight: bold; color: #2c3e50; margin-top: 4px; }

        /* Tables */
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f8f9fa; color: #2c3e50; padding: 10px; text-align: left; font-size: 11px; border-bottom: 1px solid #dee2e6; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #f0f0f0; }
        
        /* Zebra Striping */
        tbody tr:nth-child(even) { background-color: #fafafa; }
        
        .total-row { background-color: #eef2f7 !important; font-weight: bold; border-top: 1px solid #ccc; }
        .text-right { text-align: right; }
        
        .section-header { font-size: 13px; font-weight: bold; color: #2c3e50; padding: 5px 0; border-bottom: 1px solid #eee; margin-top: 15px; }
        
        .balance-box { background: #2c3e50; color: #fff; padding: 12px; border-radius: 4px; text-align: right; font-size: 15px; font-weight: bold; }
        
        footer {
        position: fixed;
        bottom: -30px; 
        left: 0;
        right: 0;
        height: 30px;
        font-size: 10px;
        color: #777;
        border-top: 1px solid #eee;
        padding-top: 5px;
        text-align: center;
    }

    /* অটোমেটিক পেজ নম্বর কাউন্টার */
    .pagenum:before {
        content: counter(page);
    }
        
    </style>
</head>
<body>

    <header>
        <table style="margin-bottom:0;">
            <tr>
                <td>
                <div class="report-title">Finance Summary-(SDF)</div>
                <div style="font-size: 12px; color: #555;">
                <strong>Report Period:</strong> 
        {{ \Carbon\Carbon::parse($from)->format('d M Y') }} 
        to 
        {{ \Carbon\Carbon::parse($to)->format('d M Y') }}
            </div>
                </td>
                <td class="meta-info">
                    <strong>Generated by:</strong> {{ auth()->user()->name ?? 'System Admin' }}<br>
                    <strong>Time:</strong> {{ now()->format('d M Y, h:i A') }}
                </td>
            </tr>
        </table>
    </header>
    
    
<footer>
    Sanatani Development Foundation (SDF) &nbsp;|&nbsp; 
    Finance Department &nbsp;|&nbsp; 
    Page <span class="pagenum"></span>
</footer>

    <div class="summary-grid">
        <div class="stat-card">
            <div class="stat-label">Total Inflow</div>
            <div class="stat-value">BDT {{ number_format($totalDonation, 2) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Total Outflow</div>
            <div class="stat-value" style="color: #c0392b;">BDT {{ number_format($totalExpense, 2) }}</div>
        </div>
        <div class="stat-card">
            <div class="stat-label">Closing Balance</div>
            <div class="stat-value">BDT {{ number_format($totalDonation - $totalExpense, 2) }}</div>
        </div>
    </div>

    <div class="section-header">Income / Donation Breakdown</div>
    <table>
        <thead><tr><th>Description</th><th class="text-right">Amount (BDT)</th></tr></thead>
        <tbody>
            <tr><td>General Donation</td><td class="text-right">{{ number_format($totalGeneralDonation, 2) }}</td></tr>
            <tr><td>Member Monthly Fees</td><td class="text-right">{{ number_format($memberMonthlyFees, 2) }}</td></tr>
            <tr><td>SDF Goods Sales</td><td class="text-right">{{ number_format($sdfGoods, 2) }}</td></tr>
            <tr><td>Collected Donation</td><td class="text-right">{{ number_format($collectedDonation, 2) }}</td></tr>
            <tr class="total-row"><td>TOTAL INCOME</td><td class="text-right">{{ number_format($totalDonation, 2) }}</td></tr>
        </tbody>
    </table>

    <div class="section-header">Expenditure Breakdown</div>
    <table>
        <thead><tr><th>Category</th><th class="text-right">Amount (BDT)</th></tr></thead>
        <tbody>
            <tr><td>Banking & Transaction Fees</td><td class="text-right">{{ number_format($bankExp, 2) }}</td></tr>
            <tr><td>Courier & Logistics</td><td class="text-right">{{ number_format($courierExp, 2) }}</td></tr>
            <tr><td>Employee Salaries & Wages</td><td class="text-right">{{ number_format($salaryExp, 2) }}</td></tr>
            <tr><td>Employee Other Allowances</td><td class="text-right">{{ number_format($empOtherExp, 2) }}</td></tr>
            <tr><td>Join Stock Expenses</td><td class="text-right">{{ number_format($joinStockExp, 2) }}</td></tr>
            <tr><td>Land & Property Maintenance</td><td class="text-right">{{ number_format($landExp, 2) }}</td></tr>
            <tr><td>Official Administrative Costs</td><td class="text-right">{{ number_format($officialExp, 2) }}</td></tr>
            <tr><td>Printing & Stationery</td><td class="text-right">{{ number_format($printingExp, 2) }}</td></tr>
            <tr><td>Advertising & Marketing</td><td class="text-right">{{ number_format($advertisingExp, 2) }}</td></tr>
            <tr><td>Educational / School Support</td><td class="text-right">{{ number_format($schoolExp, 2) }}</td></tr>
            <tr><td>Loan Repayments</td><td class="text-right">{{ number_format($loanPayExp, 2) }}</td></tr>
            <tr><td>Transport & Vehicle Fuel</td><td class="text-right">{{ number_format($transportExp, 2) }}</td></tr>
            <tr><td>Miscellaneous Others</td><td class="text-right">{{ number_format($othersExp, 2) }}</td></tr>
            <tr class="total-row"><td>TOTAL EXPENDITURE</td><td class="text-right">{{ number_format($totalExpense, 2) }}</td></tr>
        </tbody>
    </table>

    <div class="balance-box">
        Net Cash in Hand: BDT {{ number_format($totalDonation - $totalExpense, 2) }}
    </div>

</body>
</html>